// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzEIlWwi5mByDdin7vEoxmWTCgAqRk3WI',
    appId: '1:832803658321:web:e303ecb43e6dd0b140b670',
    messagingSenderId: '832803658321',
    projectId: 'pokestatscalculator',
    authDomain: 'pokestatscalculator.firebaseapp.com',
    storageBucket: 'pokestatscalculator.appspot.com',
    measurementId: 'G-RHRC7DC6PC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpINqAqXgUbv8a8lEI1AzJ9jiVznDnR_Y',
    appId: '1:832803658321:android:1ab13cb6e08582f940b670',
    messagingSenderId: '832803658321',
    projectId: 'pokestatscalculator',
    storageBucket: 'pokestatscalculator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEd-J5R1xw2mq7UECLzS9sM5Q-Yzp0ayM',
    appId: '1:832803658321:ios:355ceb7c070dd94240b670',
    messagingSenderId: '832803658321',
    projectId: 'pokestatscalculator',
    storageBucket: 'pokestatscalculator.appspot.com',
    iosClientId: '832803658321-14ju349kln4s7pql3b3u3o8uttb2goeh.apps.googleusercontent.com',
    iosBundleId: 'com.ruivop.pokestatscalculator',
  );
}
